# Site settings
title: Pentel Australia
email: patrick@theonevehicle.com
author: Patrick Dunn
description: Pentel Australia's Public Website
url: tdb

# Build settings
permalink: :title/
sass:
  sass_dir: css

#collections
collections:
  refills:
    output: true

# Social icons
show_social_icons: true
github_username: someGithubUser
twitter_username: someTwitterUser

# plugins
plugins: [jekyll-paginate]
paginate: 3

