# Site settings
title: Sample Jekyll Site With Bootstrap 4
email: patrick@theonevehicle.com
author: Patrick Dunn
description: A sample site to test Bootstrap 4 integration.
url: tdb

# Build settings
permalink: :title/
sass:
  sass_dir: css

# Social icons
show_social_icons: true
github_username: someGithubUser
twitter_username: someTwitterUser

# plugins
plugins: [jekyll-paginate]
paginate: 3